name: android-dependency-updates

on:
  schedule:
    - cron: '30 23 * * 5'

permissions:
  actions: write
  repository-projects: write

jobs:
  android-dependency-updates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Gradle check for updates
      run: ./gradlew dependencyUpdates --stacktrace
    - name: Upload dependency updates report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-report
        path: build/dependencyUpdates/report.json
        retention-days: 7
